### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by bobdabiulder** [Emaro/tictactoe#1]
Hey!  I was looking at other tic tac toe projects like the one I made in java.  Is this complete?  I like the way you are coding this, but I think some things could be done more elegantly and less manually, such as array initialization.  For what you've done so far, your code looks nice and human readable.  Compared to mine, that's a big difference.  If you do look at my project, you may be interested in my AI class.  Honestly, I'm surprised my game worked. I encourage you to try it out.  Good work, keep coding!  Best of luck 👍

**Comment by Emaro** [comment]
Oh, I'm sorry. I didn't see your comment.

No, this project is still under development. It's a school project I'm working on.

Thank you very much for your feedback! The first version should be very simple, so I don't fuck up my mind. 😄 However, later on I will make the code more generic (Maybe also not only 3x3 field).

I like your AI. Not unbeatable, but better that my current random player 😆

**Comment by bobdabiulder** [comment]
Did you actually try mine out?  I'm completely curious.  Yes, my AI is far from unbeatable.  I have discovered a few ways to beat my AI.  Just force it into a situation where there are two ways for you to win.  It can't think ahead far enough to stop you.  Loops are your friend for programs like this ;)

**Comment by Emaro** [comment]
As I still working on the base game logic, I didn't focused on the AI yet. Let's see what I'll implement in the future. ^^

**Comment by bobdabiulder** [comment]
Only time will tell :)
